config/routes.rb
Rails.application.routes.draw do
  root 'tutorials#index'
  resources :bookmarks
  resources :votes
  resources :comment_comments
  resources :comments
  resources :tutorial_categories
  resources :categories
  resources :tutorials
  resources :users
  resources :sessions, only: [:create, :new, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tutorial.rb
require 'open-uri'

class Tutorial < ApplicationRecord
  validates :title, presence: true
  validates :link, presence: true, uniqueness: true
  validates :body, presence: true

  belongs_to :user
  has_many :comments
  has_many :votes
  has_many :tutorial_categories
  has_many :categories, through: :tutorial_categories
  has_many :bookmarks

  def nokogiri_doc(url)
    Nokogiri::HTML(open(url))
  end

  def title_parse(url)
    begin
      nokogiri_doc(url).title
    rescue StandardError
      "(Website title not available.)"
    end
  end

  def favicon_parse(url)
    # base_url = url.match(/(https?:\/\/(?:www\.|(?!www))[^\s\.]+\.[^\s]{2,}|www\.[^\s]+\.[^\s]{2,})/).to_s.chop
    # base_url = url.match(/(ftp|https|http)(:\/\/[a-z]*\.[a-z]*)/).to_s
    base_url = url.match(/(https|http)(:\/\/)([a-z]*)(\.)(.*)(\.)([a-z]*)(\/)/).to_s.chop
    favicon = "http://image.flaticon.com/icons/svg/164/164996.svg"

    begin
      nokogiri_doc(url).xpath("//head/link").each do |link|
        if link.attributes['href'].value.match(/favicon/)
          favicon = link.attributes['href'].value
        end
      end
    rescue StandardError
    end

    if favicon[0] == "/"
      favicon = base_url + favicon
    end
    return favicon
  end

  def votes_total(votes)
    add = []
    votes.each do |vote|
      add << vote.value
    end
    add.reduce(:+) || 0
  end

  def find_vote(tutorial, current_user)
    vote_return = nil
    tutorial.votes.each do |vote|
      current_user.votes.each do |personal_vote|
        vote_return = vote if vote.id == personal_vote.id
      end
    end
    vote_return
  end

  def find_vote_id(tutorial, current_user)
    tutorial.votes.each do |vote|
      current_user.votes.each do |personal_vote|
        return personal_vote.id if vote.id == personal_vote.id
      end
    end
  end

end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController

  def index
    @tutorials = Tutorial.all
  end

  def create
    @tutorial = Tutorial.new(tutorial_params)
    @tutorial.thumbnail = @tutorial.favicon_parse(tutorial_params[:link])
    @tutorial.web_title = @tutorial.title_parse(tutorial_params[:link])
    if @tutorial.save
      redirect_to tutorial_path(@tutorial)
    else
      render :new
    end
  end

  def new
  end

  def show
    @tutorial = Tutorial.find(params[:id])
    @votes_total = @tutorial.votes_total(@tutorial.votes)
    @vote = @tutorial.find_vote(@tutorial, current_user)
    @vote_id = @tutorial.find_vote_id(@tutorial, current_user)
    respond_to do |f|
      f.html
      f.json { render json: { votes_total: @votes_total, vote: @vote, vote_id: @vote_id } }
    end
  end

  def update
    tutorial = Tutorial.find(params[:id])
    tutorial.thumbnail = tutorial.favicon_parse(tutorial.link)
    tutorial.web_title = tutorial.title_parse(tutorial.link)
    if tutorial.update_attributes(tutorial_params)
      #redirect_to group page at the tutorial? or tutorial is on top for signed in user?
    else
      render :edit
    end
  end

  def edit
    @tutorial = Tutorial.find(params[:id])
    redirect_to user_path(session[:user_id]) unless current_user.id == @tutorial.user_id
  end

  def destroy
    Tutorial.find(params[:id]).destroy
    redirect_to user_path(current_user)
  end

  private

    def tutorial_params
      params.require(:tutorial).permit(:title, :link, :thumbnail, :body, :user_id)
    end

end

app/helpers/tutorials_helper.rb
module TutorialsHelper

  def votes_display(votes)
     add = []
     for vote in votes
       add.push yield vote
     end
     add.reduce(:+) || 0
  end

  # same as above. just messing around.
  def display_votes(votes)
    add = []
    votes.each do |vote|
      add << vote.value
    end
    add.reduce(:+) || 0
  end

end

app/views/tutorials/_vote_hand.html.erb
<div class='votes'>
  <% if current_user %>
    <% unless does_user_vote_exist(find_vote(tutorial, current_user)) %>
      <span class='vote-hand-up' style='display:inline'><%= link_to ("<i class='fa fa-hand-o-up' aria-hidden='true'></i>").html_safe, votes_path(value: 1, tutorial_id: tutorial.id), method: :create %></span>
      <span class='vote-hand-up-blank' style='display:none'><i class='fa fa-hand-o-up' aria-hidden='true'></i></span>
    <% else %>
      <span class='vote-hand-up' style='display:none'><%= link_to ("<i class='fa fa-hand-o-up' aria-hidden='true'></i>").html_safe, votes_path(value: 1, tutorial_id: tutorial.id), method: :create %></span>
      <span class='vote-hand-up-blank' style='display:inline'><i class='fa fa-hand-o-up' aria-hidden='true'></i></span>
    <% end %>
    <span id='<%= tutorial.id %>'><%= votes_display(tutorial.votes) { |vote| vote.value } %></span>
    <% if does_user_vote_exist(find_vote(tutorial, current_user)) %>
      <span class='vote-hand-down' style='display:inline'><%= link_to ("<i class='fa fa-hand-o-down' aria-hidden='true'></i>").html_safe, find_vote(tutorial, current_user), method: :delete, url: votes_path(find_vote_id(tutorial, current_user)) %></span>
      <span class='vote-hand-down-blank' style='display:none'><i class='fa fa-hand-o-down' aria-hidden='true'></i></span>
    <% else %>
      <span class='vote-hand-down' style='display:none'><%= link_to ("<i class='fa fa-hand-o-down' aria-hidden='true'></i>").html_safe, find_vote(tutorial, current_user), method: :delete, url: votes_path(find_vote_id(tutorial, current_user)) %></span>
      <span class='vote-hand-down-blank' style='display:inline'><i class='fa fa-hand-o-down' aria-hidden='true'></i></span>
    <% end %>
  <% else %>
    <i class='fa fa-hand-o-up' aria-hidden='true'></i>
    <span id='<%= tutorial.id %>'><%= display_votes(tutorial.votes) %></span>
    <i class='fa fa-hand-o-down' aria-hidden='true'></i>
  <% end %>
</div>

app/views/tutorials/index.html.erb
<div class='index'>
<%= link_to 'Submit a Tutorial', new_tutorial_path %>

<% @tutorials.each do |tutorial| %>

    <div class='row' id='tutorial-list'>
      <a href='<%= tutorial.link %>' target='_blank'>
        <div class='col-md-1'>
          <img src="<%= tutorial.thumbnail %>" height="25" width="25" id='loading-thumbnail'>
        </div>
        <div class='col-md-2'>
          <div class='small-text' id='web-title'><%= tutorial.web_title %></div>
        </div>
      </a>
      <div class='tutorial'>
        <div class='col-md-9'>
          <h5>
            <%= link_to tutorial.title, tutorial, url: tutorial_path(tutorial), id: 'tutorial-title' %>
          </h5>
          <div><%= tutorial.body %></div>
          <div class='small-text'><%= tutorial.link %></div>
          <div class='.test' style='display:inline;'><%= render partial: '/tutorials/vote_hand', locals: { tutorial: tutorial } %></div>
        </div>
      </div>
    </div>

<% end %>
</div>

app/views/tutorials/new.html.erb
<% if current_user %>
  <%= form_for :tutorial, url: tutorials_path do |f|  %>
    <div>
      <%= f.text_field :title, placeholder: 'title', autofocus: true %>
    </div>
    <div>
      <%= f.text_field :link, placeholder: "tutorial's link", id: 'tutorial-link' %>
    </div>
    <div>
      <%= f.text_area :body, placeholder: 'description' %>
    </div>
    <div>
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>
    <div>
      <%= f.submit :submit %>
    </div>
  <% end %>
<% end %>

app/views/tutorials/show.html.erb
<img src="<%= @tutorial.thumbnail %>">
<%= @tutorial.web_title %>
<%= @tutorial.title %>
<%= @tutorial.link %>
<%= @tutorial.body %>
<% count = 0 %>
<% @tutorial.comments.each do |comment| %>
  <% comment.recursive_comments %>
  <div id='<%= comment.id %>' class='<%= count %>'>
    <div><%= comment.info[:name] %></div>
    <div><%= comment.info[:body] %></div>
    <div><%= comment.info[:parent] %></div>
  </div>
<% end %>
<div>
  <% @tutorial.comments.each do |comment| %>
    <%= comment.first_comment %>
  <% end %>
</div>
<!--
id's will be css id's and then if a parent_id is equal to any of those above id's then keep it in order but nest it
under the parent which can be distigueshed by how far right it is. So if it's parent is equal to a certain id
then give it a class which is incrementing to make it go left on the screen.
-->

<!--
Order by create time but put all children in an array?
-->